# Generated by Django 5.0.14 on 2026-09-08 18:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAnalysis',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user_firebase_uid', models.CharField(db_index=True, max_length=128)),
                ('original_filename', models.CharField(max_length=255)),
                ('storage_path', models.CharField(max_length=500)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('thumbnail_path', models.CharField(blank=True, max_length=500)),
                ('thumbnail_url', models.URLField(blank=True, max_length=1000)),
                ('image_size_bytes', models.PositiveIntegerField(default=0)),
                ('image_width', models.PositiveIntegerField(blank=True, null=True)),
                ('image_height', models.PositiveIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(default='image/jpeg', max_length=64)),
                ('symptoms', models.TextField(blank=True, default='')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, default='', max_length=32)),
                ('device_info', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('consent_given', models.BooleanField(default=False)),
                ('possible_conditions', models.JSONField(blank=True, default=list)),
                ('confidence', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=20)),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Emergency', 'Emergency')], default='Low', max_length=20)),
                ('possible_causes', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('first_aid', models.JSONField(blank=True, default=list)),
                ('red_flags', models.JSONField(blank=True, default=list)),
                ('when_to_visit_doctor', models.TextField(blank=True, default='')),
                ('doctor_speciality', models.CharField(blank=True, default='General Physician', max_length=128)),
                ('emergency_detected', models.BooleanField(db_index=True, default=False)),
                ('image_quality', models.CharField(default='good', max_length=32)),
                ('disclaimer', models.TextField(default='This analysis is AI generated and is not a medical diagnosis. Please consult a licensed doctor.')),
                ('error_message', models.TextField(blank=True, default='')),
                ('processing_time_ms', models.PositiveIntegerField(default=0)),
                ('ai_model_version', models.CharField(default='gemini-1.5-flash', max_length=64)),
                ('prompt_version', models.CharField(default='1.0.0', max_length=32)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Medical Image Analysis',
                'verbose_name_plural': 'Medical Image Analyses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_firebase_uid', '-created_at'], name='image_analy_user_fi_94385a_idx'), models.Index(fields=['status'], name='image_analy_status_84aeb3_idx'), models.Index(fields=['emergency_detected'], name='image_analy_emergen_8a18c8_idx')],
            },
        ),
    ]
