// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnFTmO4kaTKTH4BMSa9ZK5_b3a0tMvXA4',
    appId: '1:904070468761:web:16a01ff64ec9ce90a2d408',
    messagingSenderId: '904070468761',
    projectId: 'doctalk-e60b5',
    authDomain: 'doctalk-e60b5.firebaseapp.com',
    storageBucket: 'doctalk-e60b5.firebasestorage.app',
    measurementId: 'G-5QS5BZ5BHY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBqoIAjSjF0HwE4jVEgrKVD7FhkT8qw3M',
    appId: '1:904070468761:android:9135ca9e99166b4aa2d408',
    messagingSenderId: '904070468761',
    projectId: 'doctalk-e60b5',
    storageBucket: 'doctalk-e60b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp9CfbsqJx45no2nOSpyzbBjwXHM_apUU',
    appId: '1:904070468761:ios:855abc2eecf72f0ea2d408',
    messagingSenderId: '904070468761',
    projectId: 'doctalk-e60b5',
    storageBucket: 'doctalk-e60b5.firebasestorage.app',
    iosBundleId: 'com.example.doctalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp9CfbsqJx45no2nOSpyzbBjwXHM_apUU',
    appId: '1:904070468761:ios:855abc2eecf72f0ea2d408',
    messagingSenderId: '904070468761',
    projectId: 'doctalk-e60b5',
    storageBucket: 'doctalk-e60b5.firebasestorage.app',
    iosBundleId: 'com.example.doctalk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnFTmO4kaTKTH4BMSa9ZK5_b3a0tMvXA4',
    appId: '1:904070468761:web:672c517b15230671a2d408',
    messagingSenderId: '904070468761',
    projectId: 'doctalk-e60b5',
    authDomain: 'doctalk-e60b5.firebaseapp.com',
    storageBucket: 'doctalk-e60b5.firebasestorage.app',
    measurementId: 'G-WKTPQR2YW6',
  );
}
